var langs = {
	"en": {
		"lang_name": "English",
		"menu_home": "Game",
		"menu_offline": "Settings",
		"menu_about": "About",
		"menu_buy": "Buy Cryptid",
		"menu_learn": "Learn To Play",
		"map_title": "Map",
		"learn_title": "Learn to Play",
		"hint_title": "Hint",
		"about_title": "About",
		"hint_yes_button": "Yes, Show Hint",
		"hint_no_button": "No, Go Back",
		"hint_not_3": "There are no within 3 clues",
		"hint_not_2": "There are no within 2 clues",
		"hint_not_1": "There are no within 1 clues",
		"hint_not_on_on": "There are no <i>on terrain or terrain</i> clues",
		"hint_structures": "There are no clues which mention structures (either standing stones, shacks, or either)",
		"hint_terrain": "There are no clues which mention terrain of any type",
		"hint_animal": "There are no clues which mention animal territory",
		"hint_swamp": "There are no clues which mention swamp",
		"hint_mountain": "There are no clues which mention mountain",
		"hint_desert": "There are no clues which mention desert",
		"hint_forest": "There are no clues which mention forest",
		"hint_water": "There are no clues which mention water",
		"hint_on_on_swamp": "There are no <i>on terrain or terrain</i> clues involving swamp",
		"hint_on_on_water": "There are no <i>on terrain or terrain</i> clues involving water",
		"hint_on_on_forest": "There are no <i>on terrain or errain</i> clues involving forest",
		"hint_on_on_desert": "There are no <i>on terrain or terrain</i> clues involving desert",
		"hint_on_on_mountain": "There are no <i>on terrain or terrain</i> clues involving mountain",
		"hint_error": "Error generating hint",
		"hint_confirm": "This will show the hint for this game, and should only be done if all players agree. After showing the hint, make sure all other players see it as well.<br><br>Are you sure you want to show the hint?",
		"hint_confirm_yes": "Yes, Show Hint",
		"hint_confirm_no": "No, Go Back",
		"hint_show_hint": "Reveal Hint",
		"clue_title": "Clue for ?p?",
		"clue_title_plural": "Clues for ?p?",
		"clue_button_show": "Show Clue for ?p?",
		"clue_button_hide": "Hide Clue for ?p?",
		"clue_button_show_plural": "Show Clues for ?p?",
		"clue_button_hide_plural": "Hide Clues for ?p?",
		"reminder_title": "Clue Reminders",
		"reminder_instruction": "Press a button below to see your clue again",
		"reminder_instruction_plural": "Press a button below to see your clues again",
		"reminder_instruction_confirm": "Press again to show clue for ?p?",
		"reminder_instruction_confirm_plural": "Press again to show clues for ?p?",
		"reminder_instruction_hide": "Press button again to hide clue for ?p?",
		"reminder_instruction_hide_plural": "Press button again to hide clues for ?p?",
		"reminder_button": "?p?",
		"reminder_button_hide": "Hide ?p?",
		"reminder_button_show": "Show ?p?",
		"target_title": "Reveal Habitat",
		"target_button": "Press to Reveal Habitat",
		"target_confirm": "This will show which space is the creature's habitat on the map, and should only be done at the end of the game. <br><br> Are you sure you want to reveal the habitat?",
		"target_yes_button": "Yes, Reveal Habitat",
		"target_no_button": "No, Go Back",
		"share_title": "Share Game",
		"share_show_options": "Sharing options ▾",
		"share_hide_options": "Sharing options ▴",
		"share_code_label": "Game Code",
		"share_links_label": "Player Links",
		"share_copy_link": "Copy Link",
		"share_copied": "Copied!",
		"share_format_short": "Short",
		"share_format_plain": "Plain",
		"share_format_obfuscated": "Obfuscated",
		"share_players_12": "Players 1 &amp; 2",
		"share_players_34": "Players 3 &amp; 4",
		"reminder_pass_device": "↺ Show player clues passing the device",
		"quit_title": "End Game",
		"quit_button": "End Current Game",
		"quit_confirm": "This will end the current game, and will return you to the new game options. You will not be shown where the habitat was, or who had which clues. <br><br> Are you sure you want to end the current game?",
		"quit_yes_button": "Yes, End Game",
		"quit_no_button": "No, Go Back",
		"new_title": "New Game",
		"new_no_players": "Number of Players",
		"new_intro_label": "Advanced Mode",
		"new_hint_label": "Show Hint",
		"new_start_button": "Start Game",
		"new_keep_label": "Keep the same map",
		"new_solo_label": "Solo game: 1 human + 3 AI players",
		"solo_ai_title": "AI Players",
		"solo_ai_help": "AI responses and placed pieces appear here. Their clues remain hidden.",
		"solo_ai_turn_question": "AI Player ?p? asks Player ?q?.",
		"solo_ai_turn_search": "AI Player ?p? searches for the habitat.",
		"solo_ai_forced_cube": "Forced cube placed on a different legal space.",
		"solo_ai_turn_complete": "AI turn complete.",
		"solo_ai_turn": "AI Player ?p?'s turn.",
		"solo_ai_turn_no_options": "This AI could not find a legal move.",
		"solo_ai_win": "AI Player ?p? found the habitat.",
		"solo_ai_player": "AI Player",
		"solo_ai_col": "Column",
		"solo_ai_row": "Row",
		"solo_ai_ask": "Ask AI",
		"solo_setup_title": "Initial sharing",
		"solo_setup_help": "Place two of your cubes, one at a time, on spaces that cannot be the habitat according to your clue. After each cube, the three AI players place one cube each.",
		"solo_setup_status": "Initial sharing",
		"solo_setup_prompt": "Click a legal space for your first cube.",
		"solo_setup_second_cube": "Your cube is placed. Click a different legal space for your second cube.",
		"solo_setup_disc_required": "Your clue says this space could be the habitat. Place a cube on a different space.",
		"solo_turn_title": "Your turn",
		"solo_turn_question": "Question",
		"solo_turn_search": "Search",
		"solo_turn_question_player": "Ask:",
		"solo_turn_search_checkbox": "Search for habitat",
		"solo_turn_question_help": "Choose any space without a cube and ask one AI player if the habitat could be there.",
		"solo_turn_search_help": "Choose a space where your clue is satisfied, place your disc, and search with the AI players.",
		"solo_select_question_hex": "Click a space to question.",
		"solo_select_search_hex": "Click a space where your clue is satisfied to search.",
		"solo_turn_ready": "Choose Question or Search, then click a space on the map.",
		"solo_question_disc": "The AI placed a disc. Your turn ends; choose your next action.",
		"solo_place_different_cube": "A cube was placed. Click a different legal space where your clue is not satisfied; your cube will be placed there automatically.",
		"solo_invalid_cube_hex": "You cannot place a cube here. Choose a different space without a cube.",
		"solo_search_needs_disc": "You can only search a space that satisfies your own clue.",
		"solo_own_marker_exists": "You already have a marker on this space. Choose a different space.",
		"solo_search_stopped": "The search stopped at the first AI cube. Place your cube on a different legal space.",
		"solo_cube_needs_negative": "Your clue is satisfied here, so your cube must go somewhere else.",
		"solo_cube_placed": "Your cube is placed. Choose your next action.",
		"solo_human_title": "Your marker",
		"solo_human_help": "Follow the instruction below to place your piece.",
		"solo_human_selection": "Selected hex: column ?c?, row ?r?",
		"solo_human_place_prompt": "Now place your own marker on this same hex.",
		"solo_human_disc": "Place disc",
		"solo_human_cube": "Place cube",
		"solo_marker_placed": "Your marker has been placed. Keep searching.",
		"solo_win": "You win! All four clues match this hex.",
		"solo_wrong_disc": "Not a win yet: your clue does not match this hex.",
		"solo_wrong_cube": "This hex matches all clues. You needed to place a disc.",
		"error_map_change": "The map setup has been changed, please make sure you set up the pieces to match. <br /><br /> This happens when you choose not to keep the same map, or when you change mode, or when there are no more setups available for the map you were playing on.",
		"help_intro": "Advanced Mode offers more of a puzzle for players familiar with the game. <br><br> \t\t\t\t\t\tIn Advanced Mode, you could be given the opposite of a clue from normal mode, so you might get \"the habitat is <b>not</b> within two spaces of bear territory\" as your clue.<br><br> \t\t\t\t\t\tThe black structures are also used in Advanced Mode.",
		"general_ok": "OK",
		"general_bgm": "Background Music",
		"general_sfx": "Sound Effects",
		"general_retry": "Retry",
		"loading_title": "Loading",
		"loading_local": "Loading games from local storage",
		"loading_err_intro": "An error occurred while loading games:",
		"player_1": "Player 1",
		"player_2": "Player 2",
		"player_3": "Player 3",
		"player_4": "Player 4",
		"player_5": "Player 5",
		"player_12": "Players 1 &amp; 2",
		"player_34": "Players 3 &amp; 4",
		"settings_tutorial_title": "Tutorial",
		"settings_tutorial_label": "Show Tutorial",
		"settings_cryptidVersion": "Cryptid version",
		"reveal_title": "Clues",
		"tut_show": "Show Tutorial",
		"tut_title": "Tutorial",
		"tut_next": "Next",
		"tut_prev": "Prev",
		"tut_node_0": "First time playing? Press \"Next\" to get started.<br><br>Press x to close the tutorial. You can turn it back on in Settings.",
		"tut_node_1": "Cryptid is a deduction game for 3-5 players. Everyone gets one secret clue about where the habitat could be. When the clues are combined, only one space can be the habitat.<br><br>Take one matching colour set of cubes and discs per player. Keep your clue secret and answer honestly.",
		"tut_node_2": "Choose 3-5 players and start a new game. Advanced Mode adds negative clues and uses all four structures of each type, so Normal Mode is best for a first game.<br><br>For a solo game, enable \"Solo game\": you play Player 1 and three AI players answer automatically.",
		"tut_node_3": "Build the map from the six numbered tiles. Use the setup image to place and rotate each tile: the dot on a tile shows the corner containing its number.<br><br>Then place the standing stones and abandoned shacks on the indicated spaces. Normal Mode does not use the black structures.",
		"tut_node_4": "Each player receives a secret clue. A clue tells you where the habitat could be, based on terrain, animal territory, or structures.<br><br>A disc means a space could be the habitat according to your clue. A cube means it cannot. Keep your clue hidden, but always place pieces honestly.",
		"tut_node_5": "Before the first turn, complete the initial sharing. In turn order, each player places two cubes on spaces which cannot be the habitat according to their clue.<br><br>You cannot place a piece on a space containing any player’s cube. Pieces stay on the board unless a mistake is corrected.",
		"tut_node_6": "On your turn, either question or search.<br><br>To question, choose any space and ask one player if the habitat could be there. They place a disc for YES or a cube for NO. If they place a cube, you must place one of your cubes on a different legal space.",
		"tut_node_7": "To search, choose a space that could be the habitat according to your clue and place one of your discs there. Ask the other players in order. Each places a disc if their clue is satisfied or a cube if it is not.<br><br>The search stops at the first cube. If nobody places a cube, you have found the habitat and win.",
		"tut_node_8": "Use the clue reminder buttons when needed. You may not question, search, or place a piece on a space containing any cube. If one of your discs is already on a space, you cannot add another disc there.<br><br>Use Reveal Habitat only after the game, to check the answer.",
		"tut_node_9": "Solo mode follows the same logic with one human and three AI players. Your turn normally asks one selected AI; tick Search when you want to search instead. The AI players also take their own turns and may ask you or another AI.<br><br>When a search starts, the active player places a disc and the other players respond in order. If everyone places a disc, the active player wins. You can reveal the habitat after the game to check the result.",
		"within_animal": "The habitat is within one space of either animal territory",
		"within_animal_cougar": "The habitat is within two spaces of a cougar territory",
		"within_animal_bear": "The habitat is within two spaces of bear territory",
		"within_stone": "The habitat is within two spaces of a standing stone",
		"within_shack": "The habitat is within two spaces of a shack",
		"within_green": "The habitat is within three spaces of a green structure",
		"within_blue": "The habitat is within three spaces of a blue structure",
		"within_white": "The habitat is within three spaces of a white structure",
		"within_black": "The habitat is within three spaces of a black structure",
		"within_forest": "The habitat is within one space of forest",
		"within_water": "The habitat is within one space of water",
		"within_swamp": "The habitat is within one space of swamp",
		"within_mountain": "The habitat is within one space of mountain",
		"within_desert": "The habitat is within one space of desert",
		"desert_or_swamp": "The habitat is on desert or swamp",
		"forest_or_mountain": "The habitat is on forest or mountain",
		"forest_or_swamp": "The habitat is on forest or swamp",
		"mountain_or_swamp": "The habitat is on mountain or swamp",
		"water_or_mountain": "The habitat is on water or mountain",
		"forest_or_desert": "The habitat is on forest or desert",
		"water_or_forest": "The habitat is on water or forest",
		"water_or_desert": "The habitat is on water or desert",
		"water_or_swamp": "The habitat is on water or swamp",
		"desert_or_mountain": "The habitat is on desert or mountain",
		"not_within_animal": "The habitat is <b>not</b> within one space of an animal's territory",
		"not_within_animal_cougar": "The habitat is <b>not</b> within two spaces of a cougar territory",
		"not_within_animal_bear": "The habitat is <b>not</b> within two spaces of bear territory",
		"not_within_stone": "The habitat is <b>not</b> within two spaces of a standing stone",
		"not_within_shack": "The habitat is <b>not</b> within two spaces of a shack",
		"not_within_green": "The habitat is <b>not</b> within three spaces of a green structure",
		"not_within_blue": "The habitat is <b>not</b> within three spaces of a blue structure",
		"not_within_white": "The habitat is <b>not</b> within three spaces of a white structure",
		"not_within_black": "The habitat is <b>not</b> within three spaces of a black structure",
		"not_within_forest": "The habitat is <b>not</b> within one space of forest",
		"not_within_water": "The habitat is <b>not</b> within one space of water",
		"not_within_swamp": "The habitat is <b>not</b> within one space of swamp",
		"not_within_mountain": "The habitat <b>not</b> is within one space of mountain",
		"not_within_desert": "The habitat is <b>not</b> within one space of desert",
		"not_desert_or_swamp": "The habitat is <b>not</b> on desert or swamp",
		"not_forest_or_mountain": "The habitat is <b>not</b> on forest or mountain",
		"not_forest_or_swamp": "The habitat is <b>not</b> on forest or swamp",
		"not_mountain_or_swamp": "The habitat is <b>not</b> on mountain or swamp",
		"not_water_or_mountain": "The habitat is <b>not</b> on water or mountain",
		"not_forest_or_desert": "The habitat is <b>not</b> on forest or desert",
		"not_water_or_forest": "The habitat is <b>not</b> on water or forest",
		"not_water_or_desert": "The habitat is <b>not</b> on water or desert",
		"not_water_or_swamp": "The habitat is <b>not</b> on water or swamp",
		"not_desert_or_mountain": "The habitat is <b>not</b> on desert or mountain",
		"two_player_warn": "Before you begin please read the additional short rules for 2 players <a href=\"https://ospreypublishing.com/media/50in1j2t/cryptid_2player_rulesheet.pdf\" class=\"visible\" target=\"_blank\">here</a>. This mode is not recommended for first-time players.",
		"cheat_title": "Cheat Sheet",
		"cheat_show": "Cheat Sheet ▾",
		"cheat_hide": "Cheat Sheet ▴",
		"cheat_section_topography": "Topography",
		"cheat_section_clues": "Clues",
		"cheat_section_turns": "Turn Actions",
		"cheat_legend_terrain": "Terrains:",
		"cheat_legend_animal": "Animal territories:",
		"cheat_legend_structure": "Structures:",
		"cheat_terrain_water": "Water",
		"cheat_terrain_mountain": "Mountain",
		"cheat_terrain_forest": "Forest",
		"cheat_terrain_swamp": "Swamp",
		"cheat_terrain_desert": "Desert",
		"cheat_animal_cougar": "Cougar",
		"cheat_animal_bear": "Bear",
		"cheat_struct_stone": "Standing Stone",
		"cheat_struct_shack": "Shack",
		"cheat_group_on": "On one of two terrain types:",
		"cheat_group_within1": "Within 1 space of a terrain type or animal territory:",
		"cheat_group_within2": "Within 2 spaces of an animal territory or structure type:",
		"cheat_group_within3": "Within 3 spaces of a structure of a given color:",
		"cheat_turns_title": "Turn Actions ▸",
		"cheat_turns_ask_title": "Ask",
		"cheat_turns_ask_body": "Choose any hex and ask one player if their clue is satisfied there. They place a disc for YES or a cube for NO. If they place a cube, you must place one of your cubes on a different legal hex where your clue is not satisfied.",
		"cheat_turns_search_title": "Search",
		"cheat_turns_search_body": "Choose a hex where your clue is satisfied and place your own disc there. Ask every player in order. They place a disc if their clue is satisfied or a cube if it is not. The search stops at the first cube. If everyone places a disc, you win!",
		"link_learn": "https://ospreypublishing.com/uk/cryptid-9781472830654/",
		"link_buy": "https://ospreypublishing.com/uk/cryptid-9781472830654/",
		"link_home": "https://ospreypublishing.com/uk/osprey-games/",
		"solo_ai_invalid_hex": "Choose AI Player 2-4 and a valid hex: column 1-12, row 1-9.",
		"solo_ai_player_name": "AI ?p?",
		"solo_ai_answer_yes": "YES - place a disc",
		"solo_ai_answer_no": "NO - place a cube",
		"solo_ai_invalid_player": "Choose AI Player 2-4."
	},
	"fi": {
		"lang_name": "Suomi",
		"menu_home": "Peli",
		"menu_offline": "Asetukset",
		"menu_about": "Tietoja",
		"menu_buy": "Osta Cryptid",
		"menu_learn": "Opettele pelaamaan",
		"map_title": "Kartta",
		"learn_title": "Opettele pelaamaan",
		"hint_title": "Vihje",
		"about_title": "Tietoja",
		"hint_yes_button": "Kyllä, näytä vihje",
		"hint_no_button": "Ei, palaa takaisin",
		"hint_not_3": "Pelissä ei ole kolmen etäisyyden vihjeitä",
		"hint_not_2": "Pelissä ei ole kahden etäisyyden vihjeitä",
		"hint_not_1": "Pelissä ei ole yhden etäisyyden vihjeitä",
		"hint_not_on_on": "Pelissä ei ole <i>maastossa tai maastossa</i> -vihjeitä",
		"hint_structures": "Pelissä ei ole rakenteita mainitsevia vihjeitä (kivipaadet, majat tai kumpikaan niistä)",
		"hint_terrain": "Pelissä ei ole maastotyyppiä mainitsevia vihjeitä",
		"hint_animal": "Pelissä ei ole eläinalueita mainitsevia vihjeitä",
		"hint_swamp": "Pelissä ei ole suota mainitsevia vihjeitä",
		"hint_mountain": "Pelissä ei ole vuorta mainitsevia vihjeitä",
		"hint_desert": "Pelissä ei ole aavikkoa mainitsevia vihjeitä",
		"hint_forest": "Pelissä ei ole metsää mainitsevia vihjeitä",
		"hint_water": "Pelissä ei ole vettä mainitsevia vihjeitä",
		"hint_on_on_swamp": "Pelissä ei ole <i>maastossa tai maastossa</i> -vihjeitä, joissa mainitaan suo",
		"hint_on_on_water": "Pelissä ei ole <i>maastossa tai maastossa</i> -vihjeitä, joissa mainitaan vesi",
		"hint_on_on_forest": "Pelissä ei ole <i>maastossa tai maastossa</i> -vihjeitä, joissa mainitaan metsä",
		"hint_on_on_desert": "Pelissä ei ole <i>maastossa tai maastossa</i> -vihjeitä, joissa mainitaan aavikko",
		"hint_on_on_mountain": "Pelissä ei ole <i>maastossa tai maastossa</i> -vihjeitä, joissa mainitaan vuori",
		"hint_error": "Vihjeen luominen epäonnistui",
		"hint_confirm": "Tämä näyttää tämän pelin vihjeen, ja se kannattaa tehdä vain jos kaikki pelaajat ovat samaa mieltä. Kun vihje on näytetty, varmista että kaikki muutkin pelaajat näkevät sen.<br><br>Haluatko varmasti näyttää vihjeen?",
		"hint_confirm_yes": "Kyllä, näytä vihje",
		"hint_confirm_no": "Ei, palaa takaisin",
		"hint_show_hint": "Paljasta vihje",
		"clue_title": "Vihje pelaajalle ?p?",
		"clue_title_plural": "Vihjeet pelaajalle ?p?",
		"clue_button_show": "Näytä pelaajan ?p? vihje",
		"clue_button_hide": "Piilota pelaajan ?p? vihje",
		"clue_button_show_plural": "Näytä pelaajan ?p? vihjeet",
		"clue_button_hide_plural": "Piilota pelaajan ?p? vihjeet",
		"reminder_title": "Vihjemuistutukset",
		"reminder_instruction": "Paina alta painiketta nähdäksesi vihjeesi uudelleen",
		"reminder_instruction_plural": "Paina alta painiketta nähdäksesi vihjeesi uudelleen",
		"reminder_instruction_confirm": "Paina uudelleen näyttääksesi pelaajan ?p? vihjeen",
		"reminder_instruction_confirm_plural": "Paina uudelleen näyttääksesi pelaajan ?p? vihjeet",
		"reminder_instruction_hide": "Paina painiketta uudelleen piilottaaksesi pelaajan ?p? vihjeen",
		"reminder_instruction_hide_plural": "Paina painiketta uudelleen piilottaaksesi pelaajan ?p? vihjeet",
		"reminder_button": "?p?",
		"reminder_button_hide": "Piilota ?p?",
		"reminder_button_show": "Näytä ?p?",
		"target_title": "Paljasta elinpaikka",
		"target_button": "Paljasta elinpaikka",
		"target_confirm": "Tämä näyttää kartalta olennon elinpaikan, ja se kannattaa tehdä vasta pelin lopussa. <br><br> Haluatko varmasti paljastaa elinpaikan?",
		"target_yes_button": "Kyllä, paljasta elinpaikka",
		"target_no_button": "Ei, palaa takaisin",
		"share_title": "Jaa peli",
		"share_show_options": "Jakoasetukset ▾",
		"share_hide_options": "Jakoasetukset ▴",
		"share_code_label": "Pelikoodi",
		"share_links_label": "Pelaajalinkit",
		"share_copy_link": "Kopioi linkki",
		"share_copied": "Kopioitu!",
		"share_format_short": "Lyhyt",
		"share_format_plain": "Selkokielinen",
		"share_format_obfuscated": "Peitetty",
		"share_players_12": "Pelaajat 1 &amp; 2",
		"share_players_34": "Pelaajat 3 &amp; 4",
		"reminder_pass_device": "↺ Näytä pelaajien vihjeet laitetta kierrättämällä",
		"quit_title": "Lopeta peli",
		"quit_button": "Lopeta nykyinen peli",
		"quit_confirm": "Tämä lopettaa nykyisen pelin ja palauttaa sinut uuden pelin asetuksiin. Sinulle ei näytetä, missä elinpaikka oli tai mitkä vihjeet pelaajilla oli. <br><br> Haluatko varmasti lopettaa nykyisen pelin?",
		"quit_yes_button": "Kyllä, lopeta peli",
		"quit_no_button": "Ei, palaa takaisin",
		"new_title": "Uusi peli",
		"new_no_players": "Pelaajien määrä",
		"new_intro_label": "Edistynyt tila",
		"new_hint_label": "Näytä vihje",
		"new_start_button": "Aloita peli",
		"new_keep_label": "Pidä sama kartta",
		"new_solo_label": "Soolopeli: 1 ihmispelaaja + 3 AI-pelaajaa",
		"solo_ai_title": "AI-pelaajat",
		"solo_ai_help": "AI-vastaukset ja asetetut merkit näkyvät tässä. Niiden vihjeet pysyvät salassa.",
		"solo_ai_turn_question": "AI-pelaaja ?p? kysyy pelaajalta ?q?.",
		"solo_ai_turn_search": "AI-pelaaja ?p? etsii elinpaikkaa.",
		"solo_ai_forced_cube": "Pakollinen kuutio asetettiin eri sallittuun ruutuun.",
		"solo_ai_turn_complete": "AI-vuoro päättyi.",
		"solo_ai_turn": "AI-pelaajan ?p? vuoro.",
		"solo_ai_turn_no_options": "AI ei löytänyt sallittua siirtoa.",
		"solo_ai_win": "AI-pelaaja ?p? löysi elinpaikan.",
		"solo_ai_player": "AI-pelaaja",
		"solo_ai_col": "Sarake",
		"solo_ai_row": "Rivi",
		"solo_ai_ask": "Kysy AI:lta",
		"solo_setup_title": "Aloitusjako",
		"solo_setup_help": "Aseta kaksi omaa kuutiotasi yksi kerrallaan ruutuihin, jotka eivät oman vihjeesi mukaan voi olla elinpaikka. Jokaisen kuution jälkeen kolme AI-pelaajaa asettavat kukin yhden kuution.",
		"solo_setup_status": "Aloitusjako",
		"solo_setup_prompt": "Klikkaa kartalta sallittu ruutu ensimmäiselle kuutiolle.",
		"solo_setup_second_cube": "Kuutiosi on asetettu. Klikkaa eri sallittua ruutua toiselle kuutiolle.",
		"solo_setup_disc_required": "Oman vihjeesi mukaan tämä ruutu voi olla elinpaikka. Aseta kuutio eri ruutuun.",
		"solo_turn_title": "Sinun vuorosi",
		"solo_turn_question": "Kysy",
		"solo_turn_search": "Etsi",
		"solo_turn_question_player": "Kysy pelaajalta:",
		"solo_turn_search_checkbox": "Etsi elinpaikka",
		"solo_turn_question_help": "Valitse mikä tahansa kuutioton ruutu ja kysy yhdeltä AI-pelaajalta, voiko elinpaikka olla siellä.",
		"solo_turn_search_help": "Valitse ruutu, jossa oma vihjeesi toteutuu, aseta kiekkosi ja etsi yhdessä AI-pelaajien kanssa.",
		"solo_select_question_hex": "Klikkaa kartalta kysyttävä ruutu.",
		"solo_select_search_hex": "Klikkaa kartalta ruutu, jossa oma vihjeesi toteutuu.",
		"solo_turn_ready": "Valitse Kysy tai Etsi ja klikkaa sitten ruutua kartalta.",
		"solo_question_disc": "AI asetti kiekon. Vuorosi päättyy; valitse seuraava toiminto.",
		"solo_place_different_cube": "AI asetti kuution. Klikkaa eri sallittua ruutua, jossa oma vihjeesi ei toteudu; oma kuutiosi asetetaan siihen automaattisesti.",
		"solo_invalid_cube_hex": "Et voi asettaa kuutiota tähän. Valitse eri ruutu, jossa ei ole kuutiota.",
		"solo_search_needs_disc": "Voit etsiä vain ruutua, jossa oma vihjeesi toteutuu.",
		"solo_own_marker_exists": "Oma merkkisi on jo tässä ruudussa. Valitse eri ruutu.",
		"solo_search_stopped": "Etsintä päättyi ensimmäiseen AI-kuutioon. Aseta oma kuutiosi eri sallittuun ruutuun.",
		"solo_cube_needs_negative": "Oma vihjeesi toteutuu tässä ruudussa, joten kuutio pitää asettaa muualle.",
		"solo_cube_placed": "Kuutiosi on asetettu. Valitse seuraava toiminto.",
		"solo_human_title": "Oma pelimerkkisi",
		"solo_human_help": "Aseta oma merkkisi alla olevan ohjeen mukaisesti.",
		"solo_human_selection": "Valittu ruutu: sarake ?c?, rivi ?r?",
		"solo_human_place_prompt": "Aseta nyt oma merkkisi tähän samaan ruutuun.",
		"solo_human_disc": "Aseta kiekko",
		"solo_human_cube": "Aseta kuutio",
		"solo_marker_placed": "Oma merkkisi on asetettu. Jatka etsimistä.",
		"solo_win": "Voitto! Kaikki neljä vihjettä sopivat tähän ruutuun.",
		"solo_wrong_disc": "Et voittanut vielä: oma vihjeesi ei sovi tähän ruutuun.",
		"solo_wrong_cube": "Tämä ruutu sopii kaikkiin vihjeisiin. Tähän olisi pitänyt asettaa kiekko.",
		"error_map_change": "Kartan asettelu on muuttunut, joten varmista että pelin osat asetetaan uuden kartan mukaisesti. <br /><br /> Näin tapahtuu, kun et säilytä samaa karttaa, vaihdat pelitilaa tai nykyiselle kartalle ei ole enää asetelmia jäljellä.",
		"help_intro": "Edistynyt tila tarjoaa haastavamman pulman pelaajille, joille peli on jo tuttu. <br><br> Edistyneessä tilassa voit saada normaalin vihjeen vastakohdan, esimerkiksi \"elinpaikka <b>ei</b> ole kahden ruudun säteellä karhun alueesta\".<br><br> Edistyneessä tilassa käytetään myös mustia rakenteita.",
		"general_ok": "OK",
		"general_bgm": "Taustamusiikki",
		"general_sfx": "Äänitehosteet",
		"general_retry": "Yritä uudelleen",
		"loading_title": "Ladataan",
		"loading_local": "Ladataan pelejä paikallisesta tallennustilasta",
		"loading_err_intro": "Pelien lataamisessa tapahtui virhe:",
		"player_1": "Pelaaja 1",
		"player_2": "Pelaaja 2",
		"player_3": "Pelaaja 3",
		"player_4": "Pelaaja 4",
		"player_5": "Pelaaja 5",
		"player_12": "Pelaajat 1 &amp; 2",
		"player_34": "Pelaajat 3 &amp; 4",
		"settings_tutorial_title": "Opastus",
		"settings_tutorial_label": "Näytä opastus",
		"settings_cryptidVersion": "Cryptid-versio",
		"reveal_title": "Vihjeet",
		"tut_show": "Näytä opastus",
		"tut_title": "Opastus",
		"tut_next": "Seuraava",
		"tut_prev": "Edellinen",
		"tut_node_0": "Ensimmäinen pelikerta? Paina \"Seuraava\" aloittaaksesi.<br><br>Paina x sulkeaksesi opastuksen. Voit ottaa sen myöhemmin takaisin käyttöön asetuksista.",
		"tut_node_1": "Cryptid on 3-5 pelaajan päättelypeli. Jokaisella on salainen vihje siitä, missä elinpaikka voi olla. Kun vihjeet yhdistetään, vain yksi ruutu voi olla elinpaikka.<br><br>Jokainen pelaaja ottaa oman väriset kiekot ja kuutiot. Pidä vihjeesi salassa ja aseta merkit aina rehellisesti.",
		"tut_node_2": "Valitse 3-5 pelaajaa ja aloita uusi peli. Edistynyt tila lisää kielteisiä vihjeitä ja käyttää kaikki neljä rakennetta kumpaakin tyyppiä, joten normaalitila sopii ensimmäiseen peliin.<br><br>Soolopelissä valitse \"Soolopeli\": sinä olet pelaaja 1 ja kolme AI-pelaajaa vastaavat automaattisesti.",
		"tut_node_3": "Kokoa kartta kuudesta numeroidusta laatasta. Käytä asetuskuvaa laattojen sijoittamiseen ja kääntämiseen: laatan piste näyttää kulman, jossa sen numero on.<br><br>Aseta sitten kivipaadet ja hylätyt majat merkittyihin ruutuihin. Normaalitilassa mustia rakenteita ei käytetä.",
		"tut_node_4": "Jokainen pelaaja saa salaisen vihjeen. Vihje kertoo, missä elinpaikka voi olla maaston, eläinalueen tai rakenteiden perusteella.<br><br>Kiekko tarkoittaa, että ruutu voi olla elinpaikka oman vihjeesi mukaan. Kuutio tarkoittaa, ettei se voi olla. Pidä vihjeesi salassa, mutta aseta merkit aina rehellisesti.",
		"tut_node_5": "Ennen ensimmäistä vuoroa tehdään aloitusjako. Vuorojärjestyksessä jokainen pelaaja asettaa kaksi kuutiota ruutuihin, jotka eivät oman vihjeen mukaan voi olla elinpaikka.<br><br>Merkkiä ei saa asettaa ruutuun, jossa on jonkun pelaajan kuutio. Merkit jäävät laudalle, ellei virhettä korjata.",
		"tut_node_6": "Vuorollasi joko kysyt tai etsit.<br><br>Kysyessä valitse mikä tahansa ruutu ja kysy yhdeltä pelaajalta, voiko elinpaikka olla siellä. Hän asettaa kiekon, jos vastaus on kyllä, tai kuution, jos vastaus on ei. Jos hän asettaa kuution, sinun on asetettava oma kuutiosi eri sallittuun ruutuun.",
		"tut_node_7": "Etsiessä valitse ruutu, jossa elinpaikka voi oman vihjeesi mukaan olla, ja aseta siihen oma kiekkosi. Kysy muilta pelaajilta vuorojärjestyksessä. Jokainen asettaa kiekon, jos hänen vihjeensä toteutuu, tai kuution, jos se ei toteudu.<br><br>Etsintä päättyy ensimmäiseen kuutioon. Jos kukaan ei aseta kuutiota, olet löytänyt elinpaikan ja voitat.",
		"tut_node_8": "Käytä vihjemuistutuspainikkeita tarvittaessa. Et saa kysyä, etsiä tai asettaa merkkiä ruutuun, jossa on kuutio. Jos oma kiekkosi on jo ruudussa, et voi lisätä siihen toista omaa kiekkoa.<br><br>Käytä \"Paljasta elinpaikka\" -toimintoa vasta pelin jälkeen tarkistaaksesi vastauksen.",
		"tut_node_9": "Soolopeli noudattaa samaa logiikkaa: yksi ihminen ja kolme AI-pelaajaa. Vuorollasi kysyt oletuksena yhdeltä valitulta AI-pelaajalta; rastita Etsi, kun haluat etsiä. Myös AI-pelaajat pelaavat omat vuoronsa ja voivat kysyä sinulta tai toisiltaan.<br><br>Etsinnässä aktiivinen pelaaja asettaa kiekon ja muut vastaavat vuorojärjestyksessä. Jos kaikki asettavat kiekon, aktiivinen pelaaja voittaa. Voit paljastaa elinpaikan pelin jälkeen tarkistaaksesi tuloksen.",
		"within_animal": "Elinpaikka on enintään yhden ruudun päässä jommastakummasta eläinalueesta",
		"within_animal_cougar": "Elinpaikka on enintään kahden ruudun päässä puuman alueesta",
		"within_animal_bear": "Elinpaikka on enintään kahden ruudun päässä karhun alueesta",
		"within_stone": "Elinpaikka on enintään kahden ruudun päässä kivipaadesta",
		"within_shack": "Elinpaikka on enintään kahden ruudun päässä majasta",
		"within_green": "Elinpaikka on enintään kolmen ruudun päässä vihreästä rakenteesta",
		"within_blue": "Elinpaikka on enintään kolmen ruudun päässä sinisestä rakenteesta",
		"within_white": "Elinpaikka on enintään kolmen ruudun päässä valkoisesta rakenteesta",
		"within_black": "Elinpaikka on enintään kolmen ruudun päässä mustasta rakenteesta",
		"within_forest": "Elinpaikka on enintään yhden ruudun päässä metsästä",
		"within_water": "Elinpaikka on enintään yhden ruudun päässä vedestä",
		"within_swamp": "Elinpaikka on enintään yhden ruudun päässä suosta",
		"within_mountain": "Elinpaikka on enintään yhden ruudun päässä vuoresta",
		"within_desert": "Elinpaikka on enintään yhden ruudun päässä aavikosta",
		"desert_or_swamp": "Elinpaikka on aavikolla tai suolla",
		"forest_or_mountain": "Elinpaikka on metsässä tai vuorella",
		"forest_or_swamp": "Elinpaikka on metsässä tai suolla",
		"mountain_or_swamp": "Elinpaikka on vuorella tai suolla",
		"water_or_mountain": "Elinpaikka on vedessä tai vuorella",
		"forest_or_desert": "Elinpaikka on metsässä tai aavikolla",
		"water_or_forest": "Elinpaikka on vedessä tai metsässä",
		"water_or_desert": "Elinpaikka on vedessä tai aavikolla",
		"water_or_swamp": "Elinpaikka on vedessä tai suolla",
		"desert_or_mountain": "Elinpaikka on aavikolla tai vuorella",
		"not_within_animal": "Elinpaikka <b>ei</b> ole yhden ruudun päässä eläinalueesta",
		"not_within_animal_cougar": "Elinpaikka <b>ei</b> ole kahden ruudun päässä puuman alueesta",
		"not_within_animal_bear": "Elinpaikka <b>ei</b> ole kahden ruudun päässä karhun alueesta",
		"not_within_stone": "Elinpaikka <b>ei</b> ole kahden ruudun päässä pystykivestä",
		"not_within_shack": "Elinpaikka <b>ei</b> ole kahden ruudun päässä majasta",
		"not_within_green": "Elinpaikka <b>ei</b> ole kolmen ruudun päässä vihreästä rakenteesta",
		"not_within_blue": "Elinpaikka <b>ei</b> ole kolmen ruudun päässä sinisestä rakenteesta",
		"not_within_white": "Elinpaikka <b>ei</b> ole kolmen ruudun päässä valkoisesta rakenteesta",
		"not_within_black": "Elinpaikka <b>ei</b> ole kolmen ruudun päässä mustasta rakenteesta",
		"not_within_forest": "Elinpaikka <b>ei</b> ole yhden ruudun päässä metsästä",
		"not_within_water": "Elinpaikka <b>ei</b> ole yhden ruudun päässä vedestä",
		"not_within_swamp": "Elinpaikka <b>ei</b> ole yhden ruudun päässä suosta",
		"not_within_mountain": "Elinpaikka <b>ei</b> ole yhden ruudun päässä vuoresta",
		"not_within_desert": "Elinpaikka <b>ei</b> ole yhden ruudun päässä aavikosta",
		"not_desert_or_swamp": "Elinpaikka <b>ei</b> ole aavikolla eikä suolla",
		"not_forest_or_mountain": "Elinpaikka <b>ei</b> ole metsässä eikä vuorella",
		"not_forest_or_swamp": "Elinpaikka <b>ei</b> ole metsässä eikä suolla",
		"not_mountain_or_swamp": "Elinpaikka <b>ei</b> ole vuorella eikä suolla",
		"not_water_or_mountain": "Elinpaikka <b>ei</b> ole vedessä eikä vuorella",
		"not_forest_or_desert": "Elinpaikka <b>ei</b> ole metsässä eikä aavikolla",
		"not_water_or_forest": "Elinpaikka <b>ei</b> ole vedessä eikä metsässä",
		"not_water_or_desert": "Elinpaikka <b>ei</b> ole vedessä eikä aavikolla",
		"not_water_or_swamp": "Elinpaikka <b>ei</b> ole vedessä eikä suolla",
		"not_desert_or_mountain": "Elinpaikka <b>ei</b> ole aavikolla eikä vuorella",
		"two_player_warn": "Lue ennen aloittamista kahden pelaajan lisäsäännöt <a href=\"https://ospreypublishing.com/media/50in1j2t/cryptid_2player_rulesheet.pdf\" class=\"visible\" target=\"_blank\">täältä</a>. Tätä tilaa ei suositella ensikertalaisille.",
		"cheat_title": "Pikaohje",
		"cheat_show": "Pikaohje ▾",
		"cheat_hide": "Pikaohje ▴",
		"cheat_section_topography": "Maasto",
		"cheat_section_clues": "Vihjeet",
		"cheat_section_turns": "Vuorotoiminnot",
		"cheat_legend_terrain": "Maastot:",
		"cheat_legend_animal": "Eläinalueet:",
		"cheat_legend_structure": "Rakenteet:",
		"cheat_terrain_water": "Vesi",
		"cheat_terrain_mountain": "Vuori",
		"cheat_terrain_forest": "Metsä",
		"cheat_terrain_swamp": "Suo",
		"cheat_terrain_desert": "Aavikko",
		"cheat_animal_cougar": "Puuma",
		"cheat_animal_bear": "Karhu",
		"cheat_struct_stone": "Kivipaasi",
		"cheat_struct_shack": "Maja",
		"cheat_group_on": "Jommallakummalla kahdesta maastotyypistä:",
		"cheat_group_within1": "Enintään 1 ruudun päässä maastotyypistä tai eläinalueesta:",
		"cheat_group_within2": "Enintään 2 ruudun päässä eläinalueesta tai rakennetyypistä:",
		"cheat_group_within3": "Enintään 3 ruudun päässä tietyn värisestä rakenteesta:",
		"cheat_turns_title": "Vuorotoiminnot ▸",
		"cheat_turns_ask_title": "Kysy",
		"cheat_turns_ask_body": "Valitse mikä tahansa ruutu ja kysy yhdeltä pelaajalta, toteutuuko hänen vihjeensä siinä. Hän asettaa kiekon, jos vastaus on KYLLÄ, tai kuution, jos vastaus on EI. Jos hän asettaa kuution, sinun on asetettava oma kuutiosi eri sallittuun ruutuun, jossa oma vihjeesi ei toteudu.",
		"cheat_turns_search_title": "Etsi",
		"cheat_turns_search_body": "Valitse ruutu, jossa oma vihjeesi toteutuu, ja aseta siihen oma kiekkosi. Kysy muilta pelaajilta vuorojärjestyksessä. He asettavat kiekon, jos heidän vihjeensä toteutuu, tai kuution, jos se ei toteudu. Etsintä päättyy ensimmäiseen kuutioon. Jos kaikki asettavat kiekon, voitat!",
		"link_learn": "https://ospreypublishing.com/uk/cryptid-9781472830654/",
		"link_buy": "https://ospreypublishing.com/uk/cryptid-9781472830654/",
		"link_home": "https://ospreypublishing.com/uk/osprey-games/",
		"solo_ai_invalid_hex": "Valitse AI-pelaaja 2-4 ja kelvollinen ruutu: sarake 1-12, rivi 1-9.",
		"solo_ai_player_name": "AI ?p?",
		"solo_ai_answer_yes": "KYLLÄ - aseta kiekko",
		"solo_ai_answer_no": "EI - aseta kuutio",
		"solo_ai_invalid_player": "Valitse AI-pelaaja 2-4."
	}
};

var langCode;
var langForce = false;
var langData = langs["en"];
var prevCode = "";
